CREATE TABLE games (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    status TEXT NOT NULL CHECK (status <> ''),
    created_at TIMESTAMP DEFAULT NOW()
);

CREATE TABLE players (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    game_id INT REFERENCES games(id),
    name TEXT NOT NULL CHECK (name <> ''),
    total_score INT DEFAULT 0
);

CREATE TABLE rolls (
    id INTEGER PRIMARY KEY GENERATED BY DEFAULT AS IDENTITY,
    game_id INT REFERENCES games(id),
    wallet_id TEXT NOT NULL CHECK (wallet_id <> ''),
    player_id INT REFERENCES players(id),
    amount DOUBLE PRECISION NOT NULL CHECK (amount > 0);
    roll INT NOT NULL,
    created_at TIMESTAMP DEFAULT NOW()
);
